url: http://jclouds.apache.org
title: Apache jclouds
markdown: rdiscount
pygments: true
paginate: 5
paginate_path: "blog/page:num"
permalink: /blog/:categories/:year/:month/:day/:title
relative_permalinks: false
latest_version: 1.9.1
latest_version_date: 2015-08-06
latest_snapshot: 2.0.0-SNAPSHOT
